# Note: For all ENUM lists, if 'ALL' is present then the list will be treated
# as a blacklist (items listed in addition to will NOT be included).
# If there is not 'ALL' in the list, then the list will be treated as a
# whitelist (items listed WILL be included).

# Values
# BlockMethods: REMOVE, CANCEL, TP, HP
# Enchantments: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
# Entities: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
# EquipmentSlot: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/EquipmentSlot.html
# Material: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# SpawnReason: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html

Features:
  Breeding:
    BlockEntities: [ 'ALL' ] # NO animals will be allowed to breed | EquipmentSlot
    BlockClicks: false  # If true, players will not be able to feed breedable animals
    BlockBreeding: true # If true, animals will not be able to breed
    BlockLove: true     # If true, animals will not enter love mode at all
    ResetBreeding: true # If true, animals will be reset to a non-breeding state after attempting to breed
    EggThreshold: 64 # (-1 to disable)
  DaySpawns:
    CorruptionChances: # 10% Chance that a monster will spawn when a regular mob spawns
      0: 0.50 # Start of day, 6 AM
      1000: 0.30
      2000: 0.30
      3000: 0.20 # 9 AM
      4000: 0.10
      5000: 0.10
      6000: 0.10 # Midday
      7000: 0.10
      8000: 0.10
      9000: 0.20
      10000: 0.30
      11000: 0.30
      12000: 0.40 # Sunset
      13000: 0.45
      14000: 0.50
      15000: 0.55
      16000: 0.55
      17000: 0.60
      18000: 0.65 # Midnight
      19000: 0.60
      20000: 0.55
      21000: 0.50
      22000: 0.45
      23000: 0.40 # Sunrise
    LightLevels:
      SkyMin: 0
      SkyMax: 15
      BlockMin: 0
      BlockMax: 7
    RangeOffset: # The mobs can spawn up to 10 blocks away from the original mob spawn
      Min: -4
      Max: 8
    MinimumPlayerRangeSquared: 1024 # Mobs won't spawn within sqrt(1024) = 32 blocks of the player
    MobAmount: # These are WEIGHTs, currently configured to also be percentages
      1: 0.70    # 70% chance for 1 mob to spawn
      2: 0.25    # 25% for 2, etc.
      3: 0.03
      4: 0.015
      5: 0.005
      #6: 0.0001  # (Examples)
      #10: 0.00001
    MaxChunkMobs:
      # Day Cycle Image: https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/bc/Day_Night_Clock_24h.png/revision/latest?cb=20130103232456
      # 1 -> 8AM-4PM (8 hours / 6.67 minutes)
      # 2 -> 4PM-10PM (6 hours / 5 minutes)
      # 3 -> 10PM-2AM (4 hours / 3.33 minutes)
      # 2 -> 2AM-8AM (6 hours / 5 minutes)
      0: 1
      2000: 1 # 8AM
      10000: 2 # 4PM
      16000: 3 # 10PM
      20000: 2 # 2AM
  Fish:
    MinTime: 20000 # All hook events will be cancelled if they occur before this many milliseconds (-1 to disable)
    MaxTime: -1 # No hook events will be cancelled if they occur beyond this many milliseconds (-1 to disable)
    CancelChance: #  a(x+b)^c
      Constant: 80 # a
      Offset: 80 # b
      Exponent: -1 # c
    BlockEnchants: true
    AllowItems: # Material
      - COD
      - SALMON
      - TROPICAL_FISH
      - PUFFERFISH
      - LILY_PAD
      - BOWL
      - LEATHER
      - LEATHER_BOOTS
      - ROTTEN_FLESH
      - STICK
      - STRING
      - WATER_BOTTLE
      - BONE
      - INK_SAC
      - TRIPWIRE_HOOK
      - BAMBOO
      - COCOA_BEANS
  NoEnchants: # Restricts what items mobs can spawn with
    BlockEntities: # Entities
      - 'ALL'
    BlockSlots: # EquipmentSlot
      - 'ALL'
    BlockItems: # Material
      - 'ALL'
    BlockEnchants: # Enchantments
      - 'ALL'
  BlockSpawns:
    Method: CANCEL # BlockMethods
    AllowNamed: true # If true, mobs that are name tagged will remain
    BlockEntities: # Entities
      - "SHEEP"
      - "COW"
      - "BEE"
      - "PIG"
      - "OCELOT"
      - "CHICKEN"
      - "BAT"
      - "DONKEY"
      - "HORSE"
      - "FOX"
      - "MUSHROOMCOW"
      - "MULE"
      - "POLAR_BEAR"
      - "RABBIT"
      - "VILLAGER"
      - "SNOWMAN"
      - "TURTLE"
      - "PIGLIN"
      - "STRIDER"
      - "PARROT"
      - "SQUID"
      - "DOLPHIN"
      - "WOLF"
      - "CAT"
      - "PANDA"
      - "IRONGOLEM"
      - "LLAMA"
      - "COD"
      - "PUFFERFISH"
      - "SALMON"
      - "TROPICAL_FISH"
    BlockReasons: # SpawnReason
      - "NATURAL"
      - "EGG"
      - "DISPENSE_EGG"
  Apocalypse: # True if the apocalypse should auto-start
    AutoStart:
      - 'ALL'
    StartLoads: true
  Crafting: # Blocks specific item crafting
    Block: # Materials
      - 'ENCHANTING_TABLE'
    RestrictItem: 'graystainedglasspane name:&c&lDisabled! lore:&7This item is disabled!'