# Note: For all ENUM lists, if 'ALL' is present then the list will be treated
# as a blacklist (items listed in addition to will NOT be included).
# If there is not 'ALL' in the list, then the list will be treated as a
# whitelist (items listed WILL be included).

# Values
# BlockMethods: REMOVE, CANCEL, TP, HP
# Enchantments: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
# Entities: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
# EquipmentSlot: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/EquipmentSlot.html
# Material: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# SpawnReason: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html

Features:
  Breeding:
    BlockEntities: [ 'ALL' ] # NO animals will be allowed to breed | EquipmentSlot
    BlockClicks: false  # If true, players will not be able to feed breedable animals
    BlockBreeding: true # If true, animals will not be able to breed
    BlockLove: true     # If true, animals will not enter love mode at all
    ResetBreeding: true # If true, animals will be reset to a non-breeding state after attempting to breed
    EggThreshold: 64 # (-1 to disable)
  DaySpawns:
    CorruptionChances: # 10% Chance that a monster will spawn when a regular mob spawns
      0: 0.3      # Start of day, 6 AM
      1000: 0.25
      2000: 0.2
      3000: 0.1  # 9 AM
      6000: 0.05     # Midday
      9000: 0.1
      11000: 0.2
      12000: 0.25 # Sunset
      13000: 0.3
      14000: 0.35
      15000: 0.4
      16000: 0.45
      18000: 0.5  # Midnight
      21000: 0.4
      23000: 0.35 # Sunrise
    LightLevels:
      SkyMin: 0
      SkyMax: 15
      BlockMin: 0
      BlockMax: 7
    RangeOffset: # The mobs can spawn up to 10 blocks away from the original mob spawn
      Min: -10
      Max: 10
    MinimumPlayerRangeSquared: 1024 # Mobs won't spawn within sqrt(1024) = 32 blocks of the player
    MobAmount: # These are WEIGHTs, currently configured to also be percentages
      1: 0.70    # 70% chance for 1 mob to spawn
      2: 0.25    # 25% for 2, etc.
      3: 0.03
      4: 0.015
      5: 0.005
      #6: 0.0001  # (Examples)
    #10: 0.00001
    MaxChunkMobs:
      0: 4      # Start of day, 6 AM
      6000: 3     # Midday
      9000: 2
      11000: 3
      12500: 4
      14000: 5
      16000: 6
      18000: 8  # Midnight
      21000: 6
      23000: 5 # Sunrise
  Fish:
    MinTime: 20000 # All hook events will be cancelled if they occur before this many milliseconds (-1 to disable)
    MaxTime: -1 # No hook events will be cancelled if they occur beyond this many milliseconds (-1 to disable)
    CancelChance: #  a(x+b)^c
      Constant: 80 # a
      Offset: 80 # b
      Exponent: -1 # c
    BlockEnchants: true
    AllowItems: # Material
      - COD
      - SALMON
      - TROPICAL_FISH
      - PUFFERFISH
      - LILY_PAD
      - BOWL
      - LEATHER
      - LEATHER_BOOTS
      - ROTTEN_FLESH
      - STICK
      - STRING
      - WATER_BOTTLE
      - BONE
      - INK_SAC
      - TRIPWIRE_HOOK
      - BAMBOO
      - COCOA_BEANS
  NoEnchants: # Restricts what items mobs can spawn with
    BlockEntities: # Entities
      - 'ALL'
    BlockSlots: # EquipmentSlot
      - 'ALL'
      - 'HEAD'
    BlockItems: # Material
      - 'ALL'
    BlockEnchants: # Enchantments
      - 'ALL'
  BlockSpawns:
    Method: CANCEL # BlockMethods
    AllowNamed: true # If true, mobs that are name tagged will remain
    Entities: # Entities
    [ BAT, BEE, CAT, CHICKEN, COW, DONKEY, FOX, HORSE, MULE, OCELOT, PARROT, PIG, PIGLIN, POLAR_BEAR, RABBIT, SHEEP, SNOWMAN, SQUID, STRIDER, TURTLE, VILLAGER, WOLF ]
    BlockReasons: # Values (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html)
      - 'NATURAL'
  Apocalypse: # True if the apocalypse should auto-start
    AutoStart:
      - 'ALL'
    StartLoads: true
  Crafting: # Blocks specific item crafting
    Block: # Materials
      - 'ENCHANTING_TABLE'
    RestrictItem: 'graystainedglasspane name:&c&lDisabled! lore:&7This item is disabled!'