### Note: Values, Layout, Defaults, and Names are not set in stone
# This plugin is still in ALPHA and as such many things are likely to change
Features:
  Breeding:
    Entities:
      - 'ALL'
      - 'COW'
    BlockClicks: false  # If true, players will not be able to feed breedable animals
    BlockBreeding: true # If true, animals will not be able to breed
    ResetBreeding: true # If true, animals will be reset to a non-breeding state after attempting to breed
  DaySpawns:
    CorruptionChance: .1
    MobWeights:
      ZOMBIE: 0.2
      SKELETON: 0.18
    RangeOffset:
      Min: -10
      Max: 10
    MobAmount:
      1: 0.70
      2: 0.25
      3: 0.03
      4: 0.015
      5: 0.005