### Note: Values, Layout, Defaults, and Names are not set in stone
# This plugin is still in ALPHA and as such many things are likely to change
Features:
  Breeding:
    Entities:
      - 'ALL'
      - 'COW'
    BlockClicks: false  # If true, players will not be able to feed breedable animals
    BlockBreeding: true # If true, animals will not be able to breed
    ResetBreeding: true # If true, animals will be reset to a non-breeding state after attempting to breed
  DisableBreeding:
    - 'ALL'
    - 'COW'
  AllowDaySpawns:
    - 'ALL'
    - 'ZOMBIE'